### ISSUE TITLE
Fix duplication issue

### ISSUE THREAD

**Issue by sadboyzvone** [sadboyzvone/wikirider#1]
Some URLs are repeated.
I need someone to fix it.

**Comment by aamirz** [comment]
hey there! I could help you out. We can hash the links we already visited and store them -- we only visit a link if we haven't visited it before.

**Comment by sadboyzvone** [comment]
Sure!
Fork the repo,fix it and open a PR.

**Comment by sadboyzvone** [comment]
Fixed it myself, the problem is that some URLs have same names
