### ISSUE TITLE
Design a better UI

### ISSUE THREAD

**Issue by sadboyzvone** [sadboyzvone/wikirider#2]
Right now the "UI" is really colorless.
Add some feel to it, like rainbow colors or something :smiley:

**Comment by abhinuvpitale** [comment]
I would like to contribute to this, We could add a new colour to the link and the page name for each new layer of the depth.

**Comment by abhinuvpitale** [comment]
Let me know if I should start working on this.

**Comment by sadboyzvone** [comment]
Go ahead

**Comment by sadboyzvone** [comment]
Closing due to #4
