### ISSUE TITLE
Make a GUI

### ISSUE THREAD

**Issue by sadboyzvone** [sadboyzvone/wikirider#3]
If someone wants to make a GUI version go ahead

**Comment by tarix29** [comment]
What do you want the GUI to be made with? I might be able to do it with PyQt5, but that's licensed with GPL.

**Comment by sadboyzvone** [comment]
PyQt5 would be nice.

**Comment by sadboyzvone** [comment]
MIT is GPL-compatible so it doesn't really matter

**Comment by tarix29** [comment]
OK, I have also been learning tkinter, so I might end up doing it with that, or both.

**Comment by Zegram2112** [comment]
Are there any advances on this issue?. I'm interested in contributing

**Comment by sadboyzvone** [comment]
@Zegram2112 there are no advances
You can start working :))

**Comment by Zegram2112** [comment]
That's great. But, what do you think of separating wikirider in a model-view pattern? Then we could have a common model for both terminal and GUI.

**Comment by Zegram2112** [comment]
Also, I was thinking that implementing the GUI as a webpage would be interesting. Although I could do it in PyQt anyway

**Comment by sadboyzvone** [comment]
@Zegram2112 if it makes your work easier go ahead.
Speaking of a webpage, not yet.

**Comment by sadboyzvone** [comment]
Hey @Zegram2112 how's the GUI going?

**Comment by NulledRoot** [comment]
I'm going to attempt to make a GUI. I have a few ideas that might work nicely

**Comment by Sal-Ali** [comment]
Noticed the GUI issue hasn't been resolved, mind if I take a crack at it? (Well-motivated beginner here)

**Comment by sadboyzvone** [comment]
@Sal-Ali Sure take a shot!

**Comment by rgh1002** [comment]
Hey @sadboyzvone how are you doing today? I would love to take a shot at your GUI if it's still needed. I use Java and Python, do you have a preference at all? (This will be my first contribution, so whatever I submit I hope will be met with plenty of criticism so I can improve it!) Thanks!

**Comment by sadboyzvone** [comment]
Hey @rgh1002, the GUI is still needed. I obviously need it in Python but as far as the GUI framework goes, I don't really care which one you use as long as it works.

**Comment by Zegram2112** [comment]
Hey! the GUI is not finished because of college and stuff, but I can continue the development within the next days

**Comment by import-keshav** [comment]
can i make gui @sadboyzvone 
i can complete before 26.
i have experienced in making gui with tkinter

**Comment by Zegram2112** [comment]
Hey @sadboyzvone, the GUI is already working, although the first version is not finished yet. I'll make a pull request past this week

**Comment by sadboyzvone** [comment]
@mayank-kr-verma, I think @Zegram2112  already did the GUI but he forgot to make a pull request

**Comment by sadboyzvone** [comment]
@adeeb10abbas the gui is not in the master branch, if you want you can do it

**Comment by SudhanshuJoshi01** [comment]
Guys are there any further development on the issue . I would like to contribute .
